#Global settings
Count = 15 #each target will be requested this many times
Concurrency = 4 #4 concurrent requests per target, and all 3 targets are concurrent (12 total concurrent requests)
Quiet = false
Compress = true
UserAgent = "pewpewpewpewpew"
Timeout = "1.75s"
DNSPrefetch = true
Headers = "Accept-Encoding:gzip"

#Settings for each of the three Targets
[[Targets]]
    URL = "http://127.0.0.1/home" #URL is the only required field for each target
[[Targets]]
    URL = "https://127.0.0.1/api/user"
    Method = "POST"
    Body = "{\"username\": \"newuser1\", \"email\": \"newuser1@domain.com\"}"
    Headers = "Accept-Encoding:gzip, Content-Type:application/json"
    Cookies = "data=123; session=456" #equivalent to adding "Cookie: data=123; session=456," to the Header option
    Compress = true #redundant with the global Compress setting which is fine
    Timeout = "500ms" #this overwrites the explicitly set global Timeout for this target
    UserAgent = "notpewpew"
[[Targets]]
    URL = "https://127\\.0\\.0\\.1/api/user/[0-9]{1,4}" #double \\ to escape both the '.' and TOML
    RegexURL = true #parse URL with Perl syntax regex
