name: code coverage

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: calculate coverage
      run: go test -v -coverprofile=profile.cov ./...
    - name: send coverage
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
  finish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
