name: lint

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.41.1
          args: --disable-all -E errcheck -E vet -E gofmt -E misspell -E ineffassign -E goimports -E deadcode -E structcheck -E varcheck -E typecheck -E staticcheck -E gosimple ./...
